GET http://localhost:3000/login HTTP/1.1


###

POST http://localhost:3000/login 
Content-Type: application/json

{
    "name": "nome teste 5",
    "email": "email teste 5",
    "password": "senha teste 5"
}



###

GET http://localhost:3000/pedidos

###